import { useEffect, useMemo, useRef, useState } from "react";
import { BrowserMultiFormatReader } from "@zxing/browser";
import QRCode from "qrcode";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";
import { BarChart3, Camera, Check, Download, LogIn, Minus, Package, Plus, ReceiptIndianRupee, Search, ShieldCheck, ShoppingBasket, Trash2, X } from "lucide-react";

const logoUrl = "/manus-storage/kba-canteen-logo-enhanced_69b56d0b.png";
const formatINR = (value: number) => `₹${value.toFixed(2)}`;
type BillLine = { id: number; productCode: string; name: string; price: number; quantity: number; category: string };
type Tab = "billing" | "reports" | "products";

function Scanner({ onDetected, onClose }: { onDetected: (code: string) => void; onClose: () => void }) {
  const videoRef = useRef<HTMLVideoElement>(null);
  useEffect(() => { const reader = new BrowserMultiFormatReader(); let controls: { stop: () => void } | undefined; reader.decodeFromVideoDevice(undefined, videoRef.current!, (result) => { if (result) { onDetected(result.getText()); controls?.stop(); onClose(); } }).then(value => { controls = value; }).catch(() => toast.error("Camera permission is required for scanning.")); return () => controls?.stop(); }, [onClose, onDetected]);
  return <div className="modal-backdrop"><div className="scanner-card"><div className="scanner-head"><div><p className="eyebrow">Live scanner</p><h3>Scan product code</h3></div><button className="icon-button" onClick={onClose}><X size={20} /></button></div><video ref={videoRef} className="scanner-video" muted playsInline /><p className="helper">Aim the camera at a QR code or barcode. The product will be added instantly.</p></div></div>;
}

export default function Home() {
  const { user, loading, isAuthenticated } = useAuth();
  const [tab, setTab] = useState<Tab>("billing"); const [query, setQuery] = useState(""); const [lines, setLines] = useState<BillLine[]>([]); const [scannerOpen, setScannerOpen] = useState(false); const [completed, setCompleted] = useState<{ billNumber: string; total: number } | null>(null); const [productForm, setProductForm] = useState({ productCode: "", name: "", category: "", price: "", status: "active" as "active" | "disabled" }); const [editingId, setEditingId] = useState<number | null>(null);
  const utils = trpc.useUtils();
  const productsQuery = trpc.products.list.useQuery({ search: query || undefined }, { enabled: isAuthenticated && tab === "billing" }); const allProductsQuery = trpc.products.all.useQuery(undefined, { enabled: isAuthenticated && tab === "products" && user?.role === "admin" }); const reportQuery = trpc.reports.today.useQuery(undefined, { enabled: isAuthenticated && tab === "reports" });
  const createBill = trpc.bills.create.useMutation({ onSuccess: result => { setCompleted({ billNumber: result.billNumber, total: result.total }); setLines([]); utils.reports.today.invalidate(); }, onError: error => toast.error(error.message || "Bill could not be saved. Please try again.") });
  const createProduct = trpc.products.create.useMutation({ onSuccess: () => { toast.success("Product added successfully"); setProductForm({ productCode: "", name: "", category: "", price: "", status: "active" }); utils.products.all.invalidate(); }, onError: error => toast.error(error.message) }); const updateProduct = trpc.products.update.useMutation({ onSuccess: () => { toast.success("Product updated"); setEditingId(null); utils.products.all.invalidate(); }, onError: error => toast.error(error.message) }); const deleteProduct = trpc.products.remove.useMutation({ onSuccess: () => { toast.success("Product deleted"); utils.products.all.invalidate(); }, onError: error => toast.error(error.message) }); const archiveToday = trpc.reports.archiveToday.useMutation({ onSuccess: () => { toast.success("Today's sales archived"); utils.reports.today.invalidate(); } });
  const total = useMemo(() => lines.reduce((sum, line) => sum + line.price * line.quantity, 0), [lines]);
  const addProduct = (product: any) => setLines(current => { const existing = current.find(line => line.id === product.id); return existing ? current.map(line => line.id === product.id ? { ...line, quantity: line.quantity + 1 } : line) : [...current, { ...product, quantity: 1 }]; });
  const handleCode = async (code: string) => { const product = await utils.products.getByCode.fetch({ code }); if (!product) toast.error("Product not found. Please check the QR/barcode."); else { addProduct(product); toast.success(`${product.name} added`); } };
  const updateQuantity = (id: number, delta: number) => setLines(current => current.flatMap(line => line.id === id ? (line.quantity + delta <= 0 ? [] : [{ ...line, quantity: line.quantity + delta }]) : [line]));
  const completeBill = () => { if (!lines.length) return toast.error("Add at least one product before completing the bill."); createBill.mutate({ items: lines.map(line => ({ productId: line.id, quantity: line.quantity })) }); };
  const downloadCsv = async () => { const csv = await utils.reports.csv.fetch(); const url = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `kba-sales-${new Date().toISOString().slice(0, 10)}.csv`; anchor.click(); URL.revokeObjectURL(url); };
  const saveProduct = () => { const payload = { productCode: productForm.productCode, name: productForm.name, category: productForm.category, price: Number(productForm.price) }; if (editingId) updateProduct.mutate({ ...payload, id: editingId, status: productForm.status }); else createProduct.mutate(payload); }; const toggleProduct = (product: any) => updateProduct.mutate({ id: product.id, productCode: product.productCode, name: product.name, category: product.category, price: Number(product.price), status: product.status === "active" ? "disabled" : "active" }); const startEdit = (product: any) => { setEditingId(product.id); setProductForm({ productCode: product.productCode, name: product.name, category: product.category, price: String(product.price), status: product.status }); }; const generateQr = async (product: any) => { const data = await QRCode.toDataURL(product.productCode, { width: 800, margin: 2, color: { dark: "#3A1C36", light: "#FBF1FF" } }); const anchor = document.createElement("a"); anchor.href = data; anchor.download = `${product.productCode}-qr.png`; anchor.click(); };
  if (loading) return <div className="loading-screen">Loading KBA Canteen…</div>; if (!isAuthenticated) return <div className="login-screen"><div className="login-card"><img src={logoUrl} className="brand-logo large" /><p className="eyebrow">KBA Canteen operations</p><h1>Fast billing for busy hours.</h1><p className="muted">Scan, add, bill, save and report from one focused workspace.</p><Button className="primary-button wide" onClick={() => startLogin()}><LogIn size={18} /> Sign in to continue</Button></div></div>;
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><img src={logoUrl} className="brand-logo" /><div><strong>KBA Canteen</strong><span>Billing workspace</span></div></div><div className="side-label">Workspace</div><nav>{([["billing", ShoppingBasket, "Billing"], ...(user?.role === "admin" ? [["reports", BarChart3, "Today's report"], ["products", Package, "Products"]] : [])] as any[]).map(([key, Icon, label]) => <button key={key} className={`nav-item ${tab === key ? "active" : ""}`} onClick={() => setTab(key as Tab)}><Icon size={18} /> {label}</button>)}</nav><div className="sidebar-footer"><div className="role-chip"><ShieldCheck size={15} /><span>{user?.role === "admin" ? "Admin access" : "Cashier access"}</span></div><span className="timezone">Asia/Kolkata · IST</span></div></aside><main className="main-content"><header className="topbar"><div><p className="eyebrow">Good shift, {user?.name?.split(" ")[0] || "team"}</p><h1>{tab === "billing" ? "New bill" : tab === "reports" ? "Today's report" : "Product catalogue"}</h1></div><div className="topbar-status"><span className="live-dot" /> Live system</div></header>
  {tab === "billing" && <section className="billing-layout"><div className="catalog-panel"><div className="section-heading"><div><p className="eyebrow">Quick add</p><h2>Find a product</h2></div><Button className="scan-button" onClick={() => setScannerOpen(true)}><Camera size={19} /> Scan product</Button></div><div className="search-box"><Search size={19} /><Input placeholder="Search by name or code…" value={query} onChange={e => setQuery(e.target.value)} /></div><div className="product-grid">{productsQuery.isLoading ? <div className="empty-state">Loading products…</div> : productsQuery.data?.length ? productsQuery.data.map(product => <button className="product-card" key={product.id} onClick={() => addProduct(product)}><span className="product-category">{product.category}</span><strong>{product.name}</strong><span className="product-code">{product.productCode}</span><span className="product-price">{formatINR(product.price)}</span></button>) : <div className="empty-state">No active products yet. Ask an admin to add products.</div>}</div></div><div className="bill-panel"><div className="bill-panel-head"><div><p className="eyebrow">Current transaction</p><h2>Bill {lines.length ? `· ${lines.length} lines` : "· Ready"}</h2></div><button className="text-button danger" onClick={() => setLines([])} disabled={!lines.length}><Trash2 size={16} /> Clear</button></div>{completed ? <div className="completed-state"><div className="success-icon"><Check size={28} /></div><p className="eyebrow">Bill completed</p><h2>{completed.billNumber}</h2><strong>{formatINR(completed.total)}</strong><p className="muted">Saved with price snapshots at checkout.</p><Button className="primary-button" onClick={() => setCompleted(null)}>New bill</Button></div> : <><div className="bill-lines">{lines.length ? lines.map(line => <div className="bill-line" key={line.id}><div><strong>{line.name}</strong><span>{formatINR(line.price)} each</span></div><div className="quantity-control"><button onClick={() => updateQuantity(line.id, -1)}><Minus size={15} /></button><b>{line.quantity}</b><button onClick={() => updateQuantity(line.id, 1)}><Plus size={15} /></button></div><strong className="line-total">{formatINR(line.price * line.quantity)}</strong></div>) : <div className="empty-bill"><ReceiptIndianRupee size={30} /><p>Your bill is empty</p><span>Scan or tap a product to begin.</span></div>}</div><div className="bill-total"><span>Grand total</span><strong>{formatINR(total)}</strong></div><Button className="primary-button complete-button" onClick={completeBill} disabled={!lines.length || createBill.isPending}>{createBill.isPending ? "Saving…" : "Complete bill"}</Button></>}</div></section>}
  {tab === "reports" && <section className="report-page"><div className="stats-grid"><div className="stat-card"><span>Total bills</span><strong>{reportQuery.data?.totalBills ?? 0}</strong><small>Active today</small></div><div className="stat-card"><span>Items sold</span><strong>{reportQuery.data?.totalItems ?? 0}</strong><small>Across all bills</small></div><div className="stat-card accent"><span>Total sales</span><strong>{formatINR(reportQuery.data?.totalSales ?? 0)}</strong><small>Asia/Kolkata day</small></div></div><div className="report-toolbar"><div><p className="eyebrow">Transaction ledger</p><h2>Today's sales</h2></div>{user?.role === "admin" && <div className="toolbar-actions"><Button className="secondary-button" onClick={downloadCsv}><Download size={17} /> Download CSV</Button><Button className="danger-button" onClick={() => { if (confirm("Clear today's sales? Records will be archived, not deleted.")) archiveToday.mutate(); }}><Trash2 size={17} /> Clear active sales</Button></div>}</div><div className="table-card"><div className="table-row table-head"><span>Bill number</span><span>Time</span><span>Amount</span></div>{reportQuery.data?.transactions?.map(tx => <div className="table-row" key={tx.billNumber}><strong>{tx.billNumber}</strong><span>{tx.time}</span><strong>{formatINR(tx.amount)}</strong></div>)}{!reportQuery.data?.transactions?.length && <div className="empty-state">No active sales for today.</div>}</div></section>}
  {tab === "products" && user?.role === "admin" && <section className="products-page"><div className="product-admin-grid"><div className="form-card"><p className="eyebrow">Catalogue control</p><h2>{editingId ? "Edit product" : "Add product"}</h2><div className="form-stack"><Input placeholder="Product code · KBA001" value={productForm.productCode} onChange={e => setProductForm({ ...productForm, productCode: e.target.value })} /><Input placeholder="Product name" value={productForm.name} onChange={e => setProductForm({ ...productForm, name: e.target.value })} /><Input placeholder="Category" value={productForm.category} onChange={e => setProductForm({ ...productForm, category: e.target.value })} /><Input type="number" min="0" step="0.01" placeholder="Price in ₹" value={productForm.price} onChange={e => setProductForm({ ...productForm, price: e.target.value })} /><div className="form-actions"><Button className="primary-button" onClick={saveProduct}>{editingId ? "Save changes" : "Add product"}</Button>{editingId && <Button className="secondary-button" onClick={() => { setEditingId(null); setProductForm({ productCode: "", name: "", category: "", price: "", status: "active" }); }}>Cancel</Button>}</div></div></div><div className="table-card products-table"><div className="table-row table-head"><span>Product</span><span>Code</span><span>Price</span><span>Actions</span></div>{allProductsQuery.data?.map(product => <div className="table-row" key={product.id}><span><strong>{product.name}</strong><small>{product.category} · {product.status}</small></span><span>{product.productCode}</span><span>{formatINR(product.price)}</span><span className="row-actions"><button onClick={() => startEdit(product)}>Edit</button><button onClick={() => toggleProduct(product)}>{product.status === "active" ? "Disable" : "Enable"}</button><button onClick={() => generateQr(product)}><Download size={15} /></button><button onClick={() => deleteProduct.mutate({ id: product.id })}><Trash2 size={15} /></button></span></div>)}</div></div></section>}
  </main>{scannerOpen && <Scanner onDetected={handleCode} onClose={() => setScannerOpen(false)} />}</div>;
}
