import { useMemo, useState } from "react";
import { BarChart3, Check, Download, FilePlus2, Grid2X2, Minus, PackagePlus, Plus, QrCode, ReceiptIndianRupee, Settings2, ShoppingBasket, Trash2, Upload, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

const PRODUCT_KEY = "kba-local-products-v1";
const BILLS_KEY = "kba-local-bills-v1";
const SETTINGS_KEY = "kba-local-settings-v1";
const SEQUENCE_KEY = "kba-local-sequence-v1";
const LOGO_URL = "/manus-storage/kba-canteen-logo-enhanced_69b56d0b.png";
const QR_REFERENCE = "/manus-storage/paytm-qr-reference_54b65ea7.png";
const money = (value: number) => `₹${value.toFixed(2)}`;
const read = <T,>(key: string, fallback: T): T => { try { const value = localStorage.getItem(key); return value ? JSON.parse(value) : fallback; } catch { return fallback; } };
const write = (key: string, value: unknown) => localStorage.setItem(key, JSON.stringify(value));

type Product = { id: string; name: string; category: string; price: number; active: boolean; imageDataUrl?: string; createdAt: string; updatedAt: string };
type BillItem = { productId: string; productName: string; quantity: number; unitPrice: number; lineTotal: number };
type Bill = { id: string; billNumber: string; createdAt: string; archivedAt?: string; items: BillItem[]; total: number };
type Settings = { paymentQrDataUrl: string; canteenName: string; currency: string };
type View = "home" | "billing" | "reports" | "settings" | "add";

const defaultProducts: Product[] = [
  { id: "tea", name: "Tea", category: "Drinks", price: 10, active: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
  { id: "coffee", name: "Coffee", category: "Drinks", price: 15, active: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
  { id: "samosa", name: "Samosa", category: "Snacks", price: 15, active: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
];

function localDateKey(date = new Date()) { return new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Kolkata", year: "numeric", month: "2-digit", day: "2-digit" }).format(date).replaceAll("-", ""); }
function makeBillNumber() { const dateKey = localDateKey(); const seq = read<{ dateKey: string; nextNumber: number } | null>(SEQUENCE_KEY, null); const next = seq?.dateKey === dateKey ? seq.nextNumber : 1; write(SEQUENCE_KEY, { dateKey, nextNumber: next + 1 }); return `KBA-${dateKey}-${String(next).padStart(3, "0")}`; }
function readFile(file: File) { return new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = reject; reader.readAsDataURL(file); }); }

export default function Home() {
  const [view, setView] = useState<View>("home");
  const [products, setProducts] = useState<Product[]>(() => read(PRODUCT_KEY, defaultProducts));
  const [bills, setBills] = useState<Bill[]>(() => read(BILLS_KEY, []));
  const [settings, setSettings] = useState<Settings>(() => read(SETTINGS_KEY, { paymentQrDataUrl: QR_REFERENCE, canteenName: "KBA Canteen", currency: "INR" }));
  const [cart, setCart] = useState<BillItem[]>([]);
  const [search, setSearch] = useState("");
  const [editing, setEditing] = useState<Product | null>(null);
  const [completed, setCompleted] = useState<Bill | null>(null);
  const [notice, setNotice] = useState("");
  const [form, setForm] = useState({ name: "", category: "", price: "", imageDataUrl: "", active: true });
  const activeProducts = products.filter(product => product.active && `${product.name} ${product.category}`.toLowerCase().includes(search.toLowerCase()));
  const total = useMemo(() => cart.reduce((sum, item) => sum + item.lineTotal, 0), [cart]);
  const todayKey = localDateKey();
  const todayBills = bills.filter(bill => !bill.archivedAt && localDateKey(new Date(bill.createdAt)) === todayKey);
  const todayItems = todayBills.reduce((sum, bill) => sum + bill.items.reduce((inner, item) => inner + item.quantity, 0), 0);
  const todayRevenue = todayBills.reduce((sum, bill) => sum + bill.total, 0);

  const persistProducts = (next: Product[]) => { setProducts(next); write(PRODUCT_KEY, next); };
  const addToCart = (product: Product) => setCart(current => { const existing = current.find(item => item.productId === product.id); return existing ? current.map(item => item.productId === product.id ? { ...item, quantity: item.quantity + 1, lineTotal: (item.quantity + 1) * item.unitPrice } : item) : [...current, { productId: product.id, productName: product.name, quantity: 1, unitPrice: product.price, lineTotal: product.price }]; });
  const changeQty = (id: string, delta: number) => setCart(current => current.flatMap(item => item.productId === id ? (item.quantity + delta <= 0 ? [] : [{ ...item, quantity: item.quantity + delta, lineTotal: (item.quantity + delta) * item.unitPrice }]) : [item]));
  const completeBill = () => { if (!cart.length) return setNotice("Add an item before completing the bill."); const bill: Bill = { id: crypto.randomUUID(), billNumber: makeBillNumber(), createdAt: new Date().toISOString(), items: cart, total }; const next = [bill, ...bills]; setBills(next); write(BILLS_KEY, next); setCompleted(bill); setCart([]); setNotice("Bill saved locally"); };
  const saveProduct = () => { if (!form.name.trim() || !form.category.trim() || Number(form.price) <= 0) return setNotice("Enter a name, category, and valid price."); const now = new Date().toISOString(); const product: Product = { id: editing?.id || crypto.randomUUID(), name: form.name.trim(), category: form.category.trim(), price: Number(form.price), imageDataUrl: form.imageDataUrl, active: form.active, createdAt: editing?.createdAt || now, updatedAt: now }; persistProducts(editing ? products.map(item => item.id === editing.id ? product : item) : [product, ...products]); setForm({ name: "", category: "", price: "", imageDataUrl: "", active: true }); setEditing(null); setNotice("Product saved locally"); setView("settings"); };
  const editProduct = (product: Product) => { setEditing(product); setForm({ name: product.name, category: product.category, price: String(product.price), imageDataUrl: product.imageDataUrl || "", active: product.active }); setView("add"); };
  const exportCsv = () => { const rows = ["Bill Number,Date,Time,Product,Quantity,Unit Price,Total", ...todayBills.flatMap(bill => bill.items.map(item => { const date = new Date(bill.createdAt); const dateText = new Intl.DateTimeFormat("en-GB", { timeZone: "Asia/Kolkata", day: "2-digit", month: "2-digit", year: "numeric" }).format(date); const timeText = new Intl.DateTimeFormat("en-IN", { timeZone: "Asia/Kolkata", hour: "2-digit", minute: "2-digit" }).format(date); return [bill.billNumber, dateText, timeText, `"${item.productName.replaceAll('"', '""')}"`, item.quantity, item.unitPrice.toFixed(2), item.lineTotal.toFixed(2)].join(","); }))].join("\n"); const anchor = document.createElement("a"); anchor.href = URL.createObjectURL(new Blob([rows], { type: "text/csv" })); anchor.download = `kba-sales-${todayKey}.csv`; anchor.click(); setNotice("CSV downloaded"); };
  const archiveToday = () => { const next = bills.map(bill => localDateKey(new Date(bill.createdAt)) === todayKey && !bill.archivedAt ? { ...bill, archivedAt: new Date().toISOString() } : bill); setBills(next); write(BILLS_KEY, next); setNotice("Today's sales archived locally"); };
  const saveSettings = (next: Settings) => { setSettings(next); write(SETTINGS_KEY, next); setNotice("Settings saved locally"); };

  const nav = (next: View) => { setView(next); setNotice(""); };
  const tile = (next: View, icon: React.ReactNode, title: string, description: string, tone: string) => <button className={`launcher-tile ${tone}`} onClick={() => nav(next)}><span className="tile-icon">{icon}</span><strong>{title}</strong><small>{description}</small></button>;
  return <div className="local-app"><header className="local-header"><button className="mini-brand" onClick={() => nav("home")}><img src={LOGO_URL} /><span><b>{settings.canteenName}</b><small>Local kiosk</small></span></button><div className="header-meta"><span className="offline-pill"><i /> Offline ready</span><span>{new Intl.DateTimeFormat("en-IN", { timeZone: "Asia/Kolkata", dateStyle: "medium" }).format(new Date())}</span></div></header>
    {notice && <div className="notice"><Check size={16} /> {notice}<button onClick={() => setNotice("")}><X size={14} /></button></div>}
    {view === "home" && <main className="launcher"><div className="hero-copy"><p className="eyebrow">Canteen control center</p><h1>Make every order<br /><em>feel effortless.</em></h1><p>Everything you need for a fast counter shift, stored on this device and ready without a network.</p></div><div className="launcher-grid">{tile("billing", <ShoppingBasket />, "Start billing", "Tap items and build the next bill", "tile-primary")}{tile("add", <PackagePlus />, "Add item", "Create a product with photo and price", "tile-light")}{tile("settings", <Settings2 />, "Admin settings", "Products, payment QR, availability", "tile-dark")}{tile("reports", <BarChart3 />, "Daily reports", `${todayBills.length} bills · ${money(todayRevenue)}`, "tile-light")}{tile("reports", <Download />, "CSV export", "Download today's sales", "tile-outline")}</div><div className="launcher-footer"><span><Grid2X2 size={15} /> Touch-first workspace</span><span>Stored locally · Asia/Kolkata</span></div></main>}
    {view === "billing" && <main className="workspace"><div className="workspace-head"><div><button className="back-link" onClick={() => nav("home")}>← Home</button><p className="eyebrow">New transaction</p><h1>Build a bill</h1></div><Button className="dark-button" onClick={() => setCart([])}><Trash2 size={16} /> Clear bill</Button></div><div className="billing-grid"><section className="product-section"><div className="section-top"><div><h2>Choose items</h2><p>Tap a card to add one unit.</p></div><div className="search-inline"><SearchIcon /><Input placeholder="Search items" value={search} onChange={e => setSearch(e.target.value)} /></div></div><div className="item-grid">{activeProducts.map(product => <div className="item-card" key={product.id}><button className="item-hit" onClick={() => addToCart(product)}>{product.imageDataUrl ? <img src={product.imageDataUrl} /> : <span className="item-placeholder">{product.name.slice(0, 1)}</span>}<span className="item-info"><b>{product.name}</b><small>{product.category}</small><strong>{money(product.price)}</strong></span></button><span className="card-actions"><button className="minus-badge" onClick={() => changeQty(product.id, -1)}><Minus size={15} /></button><button className="plus-badge" onClick={() => addToCart(product)}><Plus size={17} /></button></span></div>)}{!activeProducts.length && <div className="empty-local">No active items. Add one from Admin settings.</div>}</div></section><aside className="bill-card"><div className="bill-card-head"><div><p className="eyebrow">Current bill</p><h2>{cart.length ? `${cart.length} items` : "Ready to start"}</h2></div><ReceiptIndianRupee /></div><div className="cart-lines">{cart.map(item => <div className="cart-line" key={item.productId}><div><b>{item.productName}</b><small>{money(item.unitPrice)} each</small></div><div className="qty"><button onClick={() => changeQty(item.productId, -1)}><Minus size={14} /></button><strong>{item.quantity}</strong><button onClick={() => changeQty(item.productId, 1)}><Plus size={14} /></button></div><strong>{money(item.lineTotal)}</strong></div>)}{!cart.length && <div className="empty-cart"><ShoppingBasket /><p>Your bill is empty</p><small>Tap any product to begin.</small></div>}</div><div className="bill-summary"><span>Total</span><strong>{money(total)}</strong></div>{settings.paymentQrDataUrl && <div className="pay-box"><div><QrCode size={17} /><span>Show payment QR</span></div><img src={settings.paymentQrDataUrl} /></div>}<Button className="primary-button complete-local" onClick={completeBill}>Complete bill</Button></aside></div></main>}
    {view === "reports" && <main className="workspace"><div className="workspace-head"><div><button className="back-link" onClick={() => nav("home")}>← Home</button><p className="eyebrow">Local ledger</p><h1>Daily reports</h1></div><div className="report-actions"><Button className="secondary-button" onClick={exportCsv}><Download size={16} /> CSV</Button><Button className="dark-button" onClick={() => { if (confirm("Archive today's sales locally?")) archiveToday(); }}><Trash2 size={16} /> Archive today</Button></div></div><div className="stats-grid local-stats"><div><small>Total bills</small><strong>{todayBills.length}</strong><span>Active today</span></div><div><small>Items sold</small><strong>{todayItems}</strong><span>Across all bills</span></div><div className="stat-emphasis"><small>Total revenue</small><strong>{money(todayRevenue)}</strong><span>Asia/Kolkata</span></div></div><div className="local-table"><div className="local-table-head"><span>Bill number</span><span>Time</span><span>Amount</span></div>{todayBills.map(bill => <div className="local-table-row" key={bill.id}><b>{bill.billNumber}</b><span>{new Intl.DateTimeFormat("en-IN", { timeZone: "Asia/Kolkata", hour: "2-digit", minute: "2-digit" }).format(new Date(bill.createdAt))}</span><strong>{money(bill.total)}</strong></div>)}{!todayBills.length && <div className="empty-local">No active bills for today.</div>}</div></main>}
    {view === "settings" && <main className="workspace"><div className="workspace-head"><div><button className="back-link" onClick={() => nav("home")}>← Home</button><p className="eyebrow">Admin control</p><h1>Settings</h1></div><Button className="primary-button" onClick={() => nav("add")}><PackagePlus size={16} /> Add item</Button></div><div className="settings-grid"><section className="settings-card"><div className="settings-card-head"><div><h2>Payment QR</h2><p>Shown on every billing screen.</p></div><QrCode /></div><img className="settings-qr" src={settings.paymentQrDataUrl} /><label className="upload-button"><Upload size={16} /> Upload new QR<input type="file" accept="image/*" onChange={async e => { const file = e.target.files?.[0]; if (file) saveSettings({ ...settings, paymentQrDataUrl: await readFile(file) }); }} /></label></section><section className="settings-card products-admin"><div className="settings-card-head"><div><h2>Product catalogue</h2><p>Tap edit to change price or availability.</p></div><PackagePlus /></div>{products.map(product => <div className="admin-product-row" key={product.id}>{product.imageDataUrl ? <img src={product.imageDataUrl} /> : <span>{product.name.slice(0, 1)}</span>}<div><b>{product.name}</b><small>{product.category} · {money(product.price)} · {product.active ? "Active" : "Disabled"}</small></div><button onClick={() => editProduct(product)}>Edit</button><button onClick={() => persistProducts(products.filter(item => item.id !== product.id))}><Trash2 size={15} /></button></div>)}</section></div></main>}
    {view === "add" && <main className="workspace"><div className="workspace-head"><div><button className="back-link" onClick={() => nav("settings")}>← Settings</button><p className="eyebrow">Admin control</p><h1>{editing ? "Edit item" : "Add item"}</h1></div></div><section className="form-card-local"><div className="form-preview">{form.imageDataUrl ? <img src={form.imageDataUrl} /> : <div><Upload size={28} /><span>Product photo</span></div>}<label className="upload-button"><Upload size={16} /> {form.imageDataUrl ? "Replace image" : "Upload image"}<input type="file" accept="image/*" onChange={async e => { const file = e.target.files?.[0]; if (file) setForm({ ...form, imageDataUrl: await readFile(file) }); }} /></label></div><div className="form-fields"><label>Product name<Input value={form.name} placeholder="e.g. Chicken Puff" onChange={e => setForm({ ...form, name: e.target.value })} /></label><label>Category<Input value={form.category} placeholder="e.g. Snacks" onChange={e => setForm({ ...form, category: e.target.value })} /></label><label>Price in ₹<Input value={form.price} type="number" min="0" step="0.01" placeholder="25" onChange={e => setForm({ ...form, price: e.target.value })} /></label><label className="switch-row"><span>Available for billing</span><input type="checkbox" checked={form.active} onChange={e => setForm({ ...form, active: e.target.checked })} /></label><Button className="primary-button save-local" onClick={saveProduct}><Check size={17} /> Save item locally</Button></div></section></main>}
    {completed && <div className="modal-backdrop"><div className="complete-modal"><div className="success-mark"><Check /></div><p className="eyebrow">Sale saved locally</p><h2>{completed.billNumber}</h2><strong>{money(completed.total)}</strong><p>Your payment QR can be shown before starting the next bill.</p><Button className="primary-button" onClick={() => { setCompleted(null); nav("billing"); }}>New bill</Button></div></div>}
  </div>;
}
function SearchIcon() { return <span className="search-icon">⌕</span>; }
