import { useMemo, useState } from "react";
import { BarChart3, Check, Download, Edit3, Minus, PackagePlus, Plus, QrCode, ShoppingBasket, Trash2, Upload, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

const PRODUCTS = "kba-local-products-v1", BILLS = "kba-local-bills-v1", SETTINGS = "kba-local-settings-v1", SEQ = "kba-local-sequence-v1";
const QR = "/manus-storage/paytm-qr-reference_54b65ea7.png", LOGO = "/manus-storage/kba-canteen-logo-enhanced_69b56d0b.png";
type Product = { id:string; name:string; category:string; price:number; active:boolean; imageDataUrl?:string; createdAt:string; updatedAt:string };
type Item = { productId:string; productName:string; quantity:number; unitPrice:number; lineTotal:number };
type Bill = { id:string; billNumber:string; createdAt:string; items:Item[]; total:number; archivedAt?:string };
type Settings = { paymentQrDataUrl:string; canteenName:string; currency:string };
type Screen = "billing"|"add"|"edit"|"reports"|"payment";
const read = <T,>(key:string, fallback:T):T => { try { const raw=localStorage.getItem(key); return raw?JSON.parse(raw):fallback; } catch { return fallback; } };
const save=(key:string,value:unknown)=>localStorage.setItem(key,JSON.stringify(value));
const money=(n:number)=>`₹${n.toFixed(2)}`;
const dateKey=(d=new Date())=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kolkata",year:"numeric",month:"2-digit",day:"2-digit"}).format(d).replaceAll("-","");
const billNo=()=>{const key=dateKey(),seq=read<{dateKey:string;nextNumber:number}|null>(SEQ,null),n=seq?.dateKey===key?seq.nextNumber:1;save(SEQ,{dateKey:key,nextNumber:n+1});return `KBA-${key}-${String(n).padStart(3,"0")}`;};
const fileData=(file:File)=>new Promise<string>((ok,fail)=>{const r=new FileReader();r.onload=()=>ok(String(r.result));r.onerror=fail;r.readAsDataURL(file);});
const defaults:Product[]=[{id:"tea",name:"Tea",category:"Drinks",price:10,active:true,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()},{id:"coffee",name:"Coffee",category:"Drinks",price:15,active:true,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()},{id:"samosa",name:"Samosa",category:"Snacks",price:15,active:true,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}];

export default function Home(){
 const [screen,setScreen]=useState<Screen>("billing"); const [products,setProducts]=useState<Product[]>(()=>read(PRODUCTS,defaults)); const [bills,setBills]=useState<Bill[]>(()=>read(BILLS,[])); const [settings,setSettings]=useState<Settings>(()=>read(SETTINGS,{paymentQrDataUrl:QR,canteenName:"KBA Canteen",currency:"INR"})); const [cart,setCart]=useState<Item[]>([]); const [category,setCategory]=useState("All"); const [search,setSearch]=useState(""); const [notice,setNotice]=useState(""); const [editing,setEditing]=useState<Product|null>(null); const [form,setForm]=useState({name:"",category:"",price:"",imageDataUrl:"",active:true});
 const categories=["All",...Array.from(new Set(products.filter(p=>p.active).map(p=>p.category))).sort()]; const visible=products.filter(p=>p.active&&(category==="All"||p.category===category)&&(`${p.name} ${p.category}`).toLowerCase().includes(search.toLowerCase())); const total=useMemo(()=>cart.reduce((s,i)=>s+i.lineTotal,0),[cart]); const today=bills.filter(b=>!b.archivedAt&&dateKey(new Date(b.createdAt))===dateKey());
 const setPs=(next:Product[])=>{setProducts(next);save(PRODUCTS,next)}; const setBs=(next:Bill[])=>{setBills(next);save(BILLS,next)};
 const add=(p:Product)=>setCart(c=>{const x=c.find(i=>i.productId===p.id);return x?c.map(i=>i.productId===p.id?{...i,quantity:i.quantity+1,lineTotal:(i.quantity+1)*i.unitPrice}:i):[...c,{productId:p.id,productName:p.name,quantity:1,unitPrice:p.price,lineTotal:p.price}]});
 const qty=(id:string,d:number)=>setCart(c=>c.flatMap(i=>i.productId!==id?[i]:i.quantity+d<=0?[]:[{...i,quantity:i.quantity+d,lineTotal:(i.quantity+d)*i.unitPrice}]));
 const nextPayment=()=>{if(!cart.length)return setNotice("Add an item first.");setScreen("payment")};
 const complete=()=>{const b:Bill={id:crypto.randomUUID(),billNumber:billNo(),createdAt:new Date().toISOString(),items:cart,total};setBs([b,...bills]);setCart([]);setNotice("Bill saved locally");setScreen("billing")};
 const openEdit=(p:Product)=>{setEditing(p);setForm({name:p.name,category:p.category,price:String(p.price),imageDataUrl:p.imageDataUrl||"",active:p.active});setScreen("edit")};
 const saveProduct=()=>{if(!form.name||!form.category||Number(form.price)<=0)return setNotice("Enter name, category and price.");const now=new Date().toISOString(),p:Product={id:editing?.id||crypto.randomUUID(),name:form.name.trim(),category:form.category.trim(),price:Number(form.price),imageDataUrl:form.imageDataUrl,active:form.active,createdAt:editing?.createdAt||now,updatedAt:now};setPs(editing?products.map(x=>x.id===editing.id?p:x):[p,...products]);setForm({name:"",category:"",price:"",imageDataUrl:"",active:true});setEditing(null);setNotice("Item saved locally");setScreen("edit")};
 const csv=()=>{const lines=["Bill Number,Date,Time,Product,Quantity,Unit Price,Total",...today.flatMap(b=>b.items.map(i=>[b.billNumber,new Intl.DateTimeFormat("en-GB",{timeZone:"Asia/Kolkata",dateStyle:"short"}).format(new Date(b.createdAt)),new Intl.DateTimeFormat("en-IN",{timeZone:"Asia/Kolkata",timeStyle:"short"}).format(new Date(b.createdAt)),`"${i.productName.replaceAll('"','""')}"`,i.quantity,i.unitPrice.toFixed(2),i.lineTotal.toFixed(2)].join(",")))].join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([lines],{type:"text/csv"}));a.download=`kba-sales-${dateKey()}.csv`;a.click()};
 const nav=(s:Screen)=>{setScreen(s);setNotice("")};
 const Bottom=()=> <nav className="bottom-menu"><button className={screen==="billing"||screen==="payment"?"active":""} onClick={()=>nav("billing")}><Home/><span>Bill</span></button><button className={screen==="add"?"active":""} onClick={()=>{setEditing(null);setForm({name:"",category:"",price:"",imageDataUrl:"",active:true});nav("add")}}><PackagePlus/><span>Add</span></button><button className={screen==="edit"?"active":""} onClick={()=>nav("edit")}><Edit3/><span>Edit</span></button><button className={screen==="reports"?"active":""} onClick={()=>nav("reports")}><BarChart3/><span>Reports</span></button></nav>;
 const Header=({title}:{title:string})=><header className="simple-header"><button onClick={()=>nav("billing")}><img src={LOGO}/><span><b>{settings.canteenName}</b><small>{title}</small></span></button><span className="local-status"><i/> Local</span></header>;
 return <div className="simple-app"><Header title={screen==="billing"?"Billing":screen==="payment"?"Payment":screen==="reports"?"Daily report":screen==="add"?"Add item":"Edit items"}/>{notice&&<div className="simple-notice"><Check size={15}/>{notice}<button onClick={()=>setNotice("")}><X size={14}/></button></div>}
 {screen==="billing"&&<main className="simple-main"><div className="billing-title"><div><p className="eyebrow">Quick counter billing</p><h1>Choose items</h1></div><span className="today-chip">{today.length} bills today</span></div><div className="category-row">{categories.map(c=><button className={category===c?"selected":""} key={c} onClick={()=>setCategory(c)}>{c}</button>)}</div><div className="simple-search"><span>⌕</span><Input placeholder="Find an item" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="simple-products">{visible.map(p=><div className="simple-product" key={p.id}><button className="simple-product-hit" onClick={()=>add(p)}>{p.imageDataUrl?<img src={p.imageDataUrl}/>:<span className="product-letter">{p.name[0]}</span>}<b>{p.name}</b><small>{p.category}</small><strong>{money(p.price)}</strong></button><div className="card-stepper"><button onClick={()=>qty(p.id,-1)}><Minus size={14}/></button><button onClick={()=>add(p)}><Plus size={16}/></button></div></div>)}{!visible.length&&<div className="simple-empty">No items in this category.</div>}</div><section className="current-bill"><div className="current-bill-head"><div><p className="eyebrow">Current bill</p><h2>{cart.length?`${cart.length} items`:"Start your order"}</h2></div><button onClick={()=>setCart([])} disabled={!cart.length}><Trash2 size={16}/> Clear</button></div>{cart.map(i=><div className="simple-line" key={i.productId}><div><b>{i.productName}</b><small>{money(i.unitPrice)} each</small></div><div className="line-stepper"><button onClick={()=>qty(i.productId,-1)}><Minus size={14}/></button><b>{i.quantity}</b><button onClick={()=>qty(i.productId,1)}><Plus size={14}/></button></div><strong>{money(i.lineTotal)}</strong></div>)}{!cart.length&&<div className="bill-empty"><ShoppingBasket/><span>Tap an item above</span></div>}<div className="simple-total"><span>Total</span><strong>{money(total)}</strong></div><Button className="next-button" onClick={nextPayment}>Next <span>→</span></Button></section></main>}
 {screen==="payment"&&<main className="simple-main payment-page"><button className="back-simple" onClick={()=>nav("billing")}>← Back to bill</button><p className="eyebrow">Step 2 of 2</p><h1>Take payment</h1><p className="payment-copy">Show this QR code to the customer, then complete the bill.</p><div className="payment-card"><QrCode/><h2>{money(total)}</h2><img src={settings.paymentQrDataUrl}/><Button className="next-button" onClick={complete}><Check size={17}/> Complete & save</Button></div></main>}
 {screen==="reports"&&<main className="simple-main"><p className="eyebrow">Saved on this device</p><h1>Daily report</h1><div className="report-cards"><div><small>Bills</small><b>{today.length}</b></div><div><small>Items</small><b>{today.reduce((s,b)=>s+b.items.reduce((x,i)=>x+i.quantity,0),0)}</b></div><div><small>Revenue</small><b>{money(today.reduce((s,b)=>s+b.total,0))}</b></div></div><Button className="report-download" onClick={csv}><Download size={16}/> Download CSV</Button><div className="report-list">{today.map(b=><div key={b.id}><b>{b.billNumber}</b><span>{new Intl.DateTimeFormat("en-IN",{timeZone:"Asia/Kolkata",timeStyle:"short"}).format(new Date(b.createdAt))}</span><strong>{money(b.total)}</strong></div>)}{!today.length&&<div className="simple-empty">No bills saved today.</div>}</div></main>}
 {(screen==="add"||screen==="edit")&&<main className="simple-main"><p className="eyebrow">Admin menu</p><h1>{editing ? "Edit item" : screen === "add" ? "Add item" : "Edit items"}</h1>{(screen==="add"||editing)&&<section className="item-form"><label>Item name<Input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Samosa"/></label><label>Category<Input value={form.category} onChange={e=>setForm({...form,category:e.target.value})} placeholder="Snacks"/></label><label>Price in ₹<Input type="number" value={form.price} onChange={e=>setForm({...form,price:e.target.value})} placeholder="15"/></label><label className="image-upload"><Upload size={17}/> {form.imageDataUrl?"Replace image":"Upload item photo"}<input type="file" accept="image/*" onChange={async e=>{const f=e.target.files?.[0];if(f)setForm({...form,imageDataUrl:await fileData(f)})}}/></label>{form.imageDataUrl&&<img className="form-image" src={form.imageDataUrl}/>}<Button className="next-button" onClick={saveProduct}><Check size={16}/> Save item</Button></section>}{screen==="edit"&&<div className="edit-list">{products.map(p=><div key={p.id}>{p.imageDataUrl?<img src={p.imageDataUrl}/>:<span>{p.name[0]}</span>}<div><b>{p.name}</b><small>{p.category} · {money(p.price)} · {p.active?"Active":"Hidden"}</small></div><button onClick={()=>openEdit(p)}>Edit</button><button onClick={()=>setPs(products.filter(x=>x.id!==p.id))}><Trash2 size={15}/></button></div>)}</div>}</main>}
 <Bottom/></div>;
}
